title: Lab
description: Documentación Oficial
layout: default
#url: https://tuusuario.github.io
aux_links:
#Repositorio:
#- https://github.com/tuusuario/open-sam

theme: minima

header_pages:
- ARQUITECTURA.md
- BITACORA_TECNICA.md
- CONTEXT.md