title: Lab
description: Documentación Oficial
theme: just-the-docs
layout: default
#url: https://tuusuario.github.io
aux_links:
#Repositorio:
#- https://github.com/tuusuario/open-sam

remote_theme: just-the-docs/just-the-docs
plugins:
- jekyll-remote-theme