create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  title text not null,
  summary text not null,
  description text,
  status text default 'active',
  year integer,
  image_url text,
  video_url text,
  open_sam_url text,
  category text,
  featured boolean default false,
  published boolean default true,
  created_at timestamptz default now()
);

create index if not exists projects_featured_idx
  on public.projects (featured);

create index if not exists projects_published_idx
  on public.projects (published);

create index if not exists projects_year_idx
  on public.projects (year);

select * from public.projects;
